[Settings]
ID = "aldreth"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  base    = ""
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "https://aldreth.netlify.com/*"
  to = "https://aldreth.com/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-ancestors 'none'"

