[Settings]
ID = "aldreth"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  base    = ""
  publish = "dist"
  command = "yarn build"
